/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ripple_adder.v:1" *)
module ripple_carry_adder_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "ripple_adder.v:2" *)
  input [3:0] a;
  (* src = "ripple_adder.v:3" *)
  input [3:0] b;
  (* src = "ripple_adder.v:4" *)
  input cin;
  (* src = "ripple_adder.v:6" *)
  output cout;
  (* src = "ripple_adder.v:5" *)
  output [3:0] sum;
  assign _00_ = ~(a[3] ^ b[3]);
  assign _01_ = a[2] & b[2];
  assign _02_ = _01_ & ~(_00_);
  assign _03_ = ~((a[3] & b[3]) | _02_);
  assign _04_ = ~(a[2] ^ b[2]);
  assign _05_ = _04_ | _00_;
  assign _06_ = ~(a[1] & b[1]);
  assign _07_ = ~(a[1] ^ b[1]);
  assign _08_ = a[0] & b[0];
  assign _09_ = a[0] ^ b[0];
  assign _10_ = ~((_09_ & cin) | _08_);
  assign _11_ = ~((_10_ | _07_) & _06_);
  assign _12_ = _05_ | ~(_11_);
  assign cout = ~(_12_ & _03_);
  assign sum[0] = _09_ ^ cin;
  assign sum[1] = _10_ ^ _07_;
  assign _13_ = ~_04_;
  assign sum[2] = _11_ ^ _13_;
  assign _14_ = ~((_11_ & _13_) | _01_);
  assign sum[3] = _14_ ^ _00_;
endmodule
