/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "ripple_adder.v:1.1-11.10" *)
module ripple_carry_adder_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  wire _18_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  wire _19_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  wire _20_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  wire _21_;
  (* src = "ripple_adder.v:3.17-3.18" *)
  wire _22_;
  (* src = "ripple_adder.v:3.17-3.18" *)
  wire _23_;
  (* src = "ripple_adder.v:3.17-3.18" *)
  wire _24_;
  (* src = "ripple_adder.v:3.17-3.18" *)
  wire _25_;
  (* src = "ripple_adder.v:4.11-4.14" *)
  wire _26_;
  (* src = "ripple_adder.v:6.12-6.16" *)
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "ripple_adder.v:5.18-5.21" *)
  wire _35_;
  (* src = "ripple_adder.v:5.18-5.21" *)
  wire _36_;
  (* src = "ripple_adder.v:5.18-5.21" *)
  wire _37_;
  (* src = "ripple_adder.v:5.18-5.21" *)
  wire _38_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "ripple_adder.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "ripple_adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "ripple_adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "ripple_adder.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hs__xnor2_1 _39_ (
    .A(_20_),
    .B(_24_),
    .Y(_28_)
  );
  sky130_fd_sc_hs__xnor2_1 _40_ (
    .A(_18_),
    .B(_22_),
    .Y(_29_)
  );
  sky130_fd_sc_hs__maj3_1 _41_ (
    .A(_18_),
    .B(_22_),
    .C(_26_),
    .X(_30_)
  );
  sky130_fd_sc_hs__xnor2_1 _42_ (
    .A(_19_),
    .B(_23_),
    .Y(_31_)
  );
  sky130_fd_sc_hs__maj3_1 _43_ (
    .A(_19_),
    .B(_23_),
    .C(_30_),
    .X(_32_)
  );
  sky130_fd_sc_hs__maj3_1 _44_ (
    .A(_20_),
    .B(_24_),
    .C(_32_),
    .X(_33_)
  );
  sky130_fd_sc_hs__xnor2_1 _45_ (
    .A(_21_),
    .B(_25_),
    .Y(_34_)
  );
  sky130_fd_sc_hs__maj3_1 _46_ (
    .A(_21_),
    .B(_25_),
    .C(_33_),
    .X(_27_)
  );
  sky130_fd_sc_hs__xnor2_1 _47_ (
    .A(_26_),
    .B(_29_),
    .Y(_35_)
  );
  sky130_fd_sc_hs__xnor2_1 _48_ (
    .A(_30_),
    .B(_31_),
    .Y(_36_)
  );
  sky130_fd_sc_hs__xnor2_1 _49_ (
    .A(_28_),
    .B(_32_),
    .Y(_37_)
  );
  sky130_fd_sc_hs__xnor2_1 _50_ (
    .A(_33_),
    .B(_34_),
    .Y(_38_)
  );
  assign _21_ = a[3];
  assign _25_ = b[3];
  assign _20_ = a[2];
  assign _24_ = b[2];
  assign _19_ = a[1];
  assign _23_ = b[1];
  assign _18_ = a[0];
  assign _22_ = b[0];
  assign _26_ = cin;
  assign cout = _27_;
  assign sum[0] = _35_;
  assign sum[1] = _36_;
  assign sum[2] = _37_;
  assign sum[3] = _38_;
endmodule
