/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "ripple_adder.v:1.1-11.10" *)
module ripple_carry_adder_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "ripple_adder.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "ripple_adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "ripple_adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "ripple_adder.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hs__xnor2_1 _07_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_00_)
  );
  sky130_fd_sc_hs__xnor2_1 _08_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hs__maj3_1 _09_ (
    .A(a[0]),
    .B(b[0]),
    .C(cin),
    .X(_02_)
  );
  sky130_fd_sc_hs__xnor2_1 _10_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hs__maj3_1 _11_ (
    .A(a[1]),
    .B(b[1]),
    .C(_02_),
    .X(_04_)
  );
  sky130_fd_sc_hs__maj3_1 _12_ (
    .A(a[2]),
    .B(b[2]),
    .C(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hs__xnor2_1 _13_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hs__maj3_1 _14_ (
    .A(a[3]),
    .B(b[3]),
    .C(_05_),
    .X(cout)
  );
  sky130_fd_sc_hs__xnor2_1 _15_ (
    .A(cin),
    .B(_01_),
    .Y(sum[0])
  );
  sky130_fd_sc_hs__xnor2_1 _16_ (
    .A(_02_),
    .B(_03_),
    .Y(sum[1])
  );
  sky130_fd_sc_hs__xnor2_1 _17_ (
    .A(_00_),
    .B(_04_),
    .Y(sum[2])
  );
  sky130_fd_sc_hs__xnor2_1 _18_ (
    .A(_05_),
    .B(_06_),
    .Y(sum[3])
  );
endmodule
