/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "ripple_adder.v:1.1-11.10" *)
module ripple_carry_adder_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "ripple_adder.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "ripple_adder.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "ripple_adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "ripple_adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "ripple_adder.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  assign _00_ = a[3] & b[3];
  assign _01_ = a[3] ^ b[3];
  assign _02_ = ~(a[2] & b[2]);
  assign _03_ = _01_ & ~(_02_);
  assign _04_ = _03_ | _00_;
  assign _05_ = ~(a[2] ^ b[2]);
  assign _06_ = _01_ & ~(_05_);
  assign _07_ = ~(a[1] & b[1]);
  assign _08_ = a[1] ^ b[1];
  assign _09_ = ~(a[0] & b[0]);
  assign _10_ = ~(a[0] ^ b[0]);
  assign _11_ = cin & ~(_10_);
  assign _12_ = _09_ & ~(_11_);
  assign _13_ = _08_ & ~(_12_);
  assign _14_ = _07_ & ~(_13_);
  assign _15_ = _06_ & ~(_14_);
  assign cout = _15_ | _04_;
  assign sum[0] = ~(_10_ ^ cin);
  assign sum[1] = ~(_12_ ^ _08_);
  assign sum[2] = _14_ ^ _05_;
  assign _16_ = ~(_14_ | _05_);
  assign _17_ = _16_ | ~(_02_);
  assign sum[3] = _17_ ^ _01_;
endmodule
